module Imessage where

--import Imessage.Internal

imessageOsaScript :: [Char]
imessageOsaScript = concat [
        "on waitUntilRunning(appname, delaytime)\n",
        "    repeat until my appIsRunning(appname)\n",
        "        tell application \"Messages\" to close window 1\n",
        "        delay delaytime\n",
        "    end repeat\n",
        "\n",
        "    delay delaytime\n",
        "end waitUntilRunning\n",
        "\n",
        "on appIsRunning(appName)\n",
        "    application appname is running\n",
        "end appIsRunning\n",
        "\n",
        "on SysevAppIsRunning(appName)\n",
        "    tell application \"System Events\" to (name of processes) contains appName\n",
        "end appIsRunning\n",
        "\n",
        "on finderAppIsRunning(appName)\n",
        "    tell application \"Finder\" to (name of every process) contains appName\n",
        "end appIsRunning\n",
        "\n",
        "on run {targetBuddyPhone, targetMessage}\n",
        "    tell application \"Messages\"\n",
        "        set wasRunning to true\n",
        "        if it is not running then\n",
        "            set wasRunning to false\n",
        "            launch\n",
        "            close window 1\n",
        "            my waitUntilRunning(\"Messages\", 1)\n",
        "            close window 1\n",
        "        end if\n",
        "\n",
        "        set targetBuddy to buddy targetBuddyPhone\n",
        "        set targetService to service of buddy targetBuddyPhone\n",
        "        send targetMessage to targetBuddy\n",
        "\n",
        "        if not wasRunning\n",
        "            close window 1\n",
        "        end if\n",
        "    end tell\n",
        "end run\n"]
